import { NextRequest, NextResponse } from 'next/server'
import { createHmac } from 'crypto'
import { readFile } from 'fs/promises'
import { join } from 'path'

// Validates the HMAC token and serves the XLS file
// Token is generated by /api/xls-purchase/verify and expires in 1 hour
export async function GET(req: NextRequest) {
  const token     = req.nextUrl.searchParams.get('token')
  const expStr    = req.nextUrl.searchParams.get('exp')
  const sessionId = req.nextUrl.searchParams.get('session_id')

  if (!token || !expStr || !sessionId) {
    return new NextResponse('Missing parameters', { status: 400 })
  }

  const exp = parseInt(expStr, 10)
  const now = Math.floor(Date.now() / 1000)

  // Check expiry
  if (now > exp) {
    return new NextResponse('Download link expired. Please return to your confirmation page to get a new link.', { status: 410 })
  }

  // Verify HMAC
  const secret  = process.env.XLS_DOWNLOAD_SECRET!
  const payload = `${sessionId}:${exp}`
  const expected = createHmac('sha256', secret).update(payload).digest('hex')

  if (token !== expected) {
    return new NextResponse('Invalid download token', { status: 403 })
  }

  // Serve the file
  try {
    const filePath = join(process.cwd(), 'public', 'downloads', 'bridge-planner-pro-v3.xlsx')
    const fileBuffer = await readFile(filePath)

    return new NextResponse(fileBuffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': 'attachment; filename="Bridge-Planner-Pro-v3.xlsx"',
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    console.error('XLS file read error:', err)
    return new NextResponse('File not found', { status: 404 })
  }
}